### ISSUE TITLE
Feature: Grafana variable support

### ISSUE THREAD

**Issue by kovaxur** [plixer/scrutinizer-datasource#1]
Hi,
It would be great to be able to use the template mechanism of Grafana. For this, we would need to be able to set up variables for the dashboards, but as I see, now it's not supported by the plugin.

Use case:
- Create a generic dashboard, with some pre-defined reports, where the name of the exporter and the name of the interface can be chosen by the user, so the report will be generated automatically.

The query format could be similar to this: https://alexanderzobnin.github.io/grafana-zabbix/guides/templating/

So for example: {hostname}{interface name}

Thanks,
Daniel

**Comment by briandav22** [comment]
Hi Daniel, 

Took me a little bit of research, but I think I get what your asking for. 

If i'm understanding, this feature would allow the following  : 

I could create a dashboard with a few reports (Top Application, Top Countries, Top Sources, Etc.) 
I would have a drop down at the top of the dashboard for "Exporter" and "Interface". When I modify the exporter and interface, all of the reports update to reflect that Router / Interface. 

This prevents the user from having to create or edit a wide variety of reports if they wanted to just flip through devices quickly. 

Am I understanding this correctly?

If so, I think i can implement this feature. The one thing i'm going to need to figure out is how to protect a user that wants disparate data on a dashboard. Maybe a dashboard with multiple devices, etc. I'm sure I can noodle out the logic of how to do this, but before I start working on it, I want to be sure i'm understanding completely what you would want as a template variable.

**Comment by kovaxur** [comment]
Hi,
Yes, with this, we can create generic dashboards, and then we can re-use them, for example something like this:
https://www.ibm.com/developerworks/community/blogs/0587adbc-8477-431f-8c68-9226adea11ed/resource/BLOGS_UPLOADED_IMAGES/Sample_LinuxOS_dashboard_animated.gif

**Comment by briandav22** [comment]
Making some progress on this, I'm going to try to have a branch posted soon for testing.

**Comment by briandav22** [comment]
Hello Daniel, 

I wanted to check if this is looking better for you? Currently I have it working where you can add and Exporter / Interface as an ad-hoc filter to a dashboard. 

It's still a little finicky so I have some more work to do, I would also like the ability to add additional filters, for example a IP Host in addition to the Exporter. More to come but I wanted to verify this is on the right track. 

![dashboard](https://user-images.githubusercontent.com/32676990/66165502-dc308080-e602-11e9-9b08-1e2d3a5c88e4.png)

**Comment by kovaxur** [comment]
Hi Brian,
Yes, looks good! 

For us, viewing specific flows between source/destination ip/ports can be intresting too

Thanks

**Comment by briandav22** [comment]
This is starting to feel a little more stable. I also added int he ability to filter for an IP address. 

I'm going to add a few more filter types. I'll probably have you test it on the branch to make sure it's all good before merging into the master. 

Here is an updated screen capture. 
![image](https://user-images.githubusercontent.com/32676990/66681234-4919cb00-ec40-11e9-88c7-f4a6c12577ff.png)

**Comment by egreenspan2** [comment]
> 
> 
> This is starting to feel a little more stable. I also added int he ability to filter for an IP address.
> 
> I'm going to add a few more filter types. I'll probably have you test it on the branch to make sure it's all good before merging into the master.
> 
> Here is an updated screen capture.
> ![image](https://user-images.githubusercontent.com/32676990/66681234-4919cb00-ec40-11e9-88c7-f4a6c12577ff.png)

This is a much needed feature, I have been playing with using variables, but this will take it to the next level.

**Comment by briandav22** [comment]
Ok after some testing I merged this into the main branch and updated the documentation. 

[https://grafana-docs.readthedocs.io/en/latest/ah_adhocFilters.html](url)
To update this you would need to go into the directory where the current datasource lives and do a 'git pull' to grab the changes. 

Please report back any bugs you find with this update. It was a significant code change...hopefully she works = ). 
Let me know!
