### ISSUE TITLE
QueryCtrl and query editor

### ISSUE THREAD

**Issue by md-mhv** [plixer/scrutinizer-datasource#9]
Grafana v7.1 no longer displays the query editor within the panel. I tried deleting and re-adding the datasource

![image](https://user-images.githubusercontent.com/68555596/88968429-52caf880-d27d-11ea-9c7f-9d76a58c8805.png)

If you toggle text edit mode you get this;
![image](https://user-images.githubusercontent.com/68555596/88968505-6ece9a00-d27d-11ea-9eff-2fcca1813006.png)

**Comment by briandav22** [comment]
@md-mhv Thank you for reporting this bug. It seems that Grafana changed their defaults in the new UI, I was able to fix this issue by altering the HTML in the query editor slightly. 

If you go to the datasource and issue a 'git pull' to grab the latest revision, the issue should be fixed.
